import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SolanaWalletProvider from "../provider/SolanaWalletProvider";
import NavBar from "@/components/NavBar";
import QueryProvider from "@/provider/QueryProvider";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "El Solar booking DApp",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-dvh flex flex-col`}
      >
        <QueryProvider>
          <SolanaWalletProvider>
            <NavBar />
            <main className="pt-20 pb-20 flex-1">{children}</main>
            <Footer />
          </SolanaWalletProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
